### PR TITLE
Add a `fallback.svg` for dynamic fallbacks

### PR DESCRIPTION
**Pull request by danielbachhuber**
See #33

Example usage:
* https://unavatar-one.vercel.app/fallback.svg?text=DB
* https://unavatar-one.vercel.app/fallback.svg?text=DB&start=9AEF00&end=00C0F7

### CODE REVIEW

**Comment by Kikobeats** [comment]
wow thanks for that, it looks pretty sick!

Your current implementation is using it as a provider. I think I like that idea and we can rename it into "identicon" since the fallback query parameter is already implemented.

what do you think about generating the color in a pseudo-random way, so the user doesn't need to think about `start` and `end`?

For example, you can generate those value based on the `text` input

**Comment by danielbachhuber** [comment]
> Your current implementation is using it as a provider. I think I like that idea and we can rename it into "identicon" since the fallback query parameter is already implemented.

Ah, yeah, that'd be a better approach. To confirm, rename my `fallback.svg` to `identicon.svg`, and keep the same query params for controlling it?

> what do you think about generating the color in a pseudo-random way, so the user doesn't need to think about `start` and `end`?

Do you have an algorithm you'd suggest? I'd like to keep the parameters as options so I can control the color in my app.

Oh, another thought: I defaulted to a solid color because I thought that might be nicer than a random gradient.

**Comment by Kikobeats** [comment]
We can implement this solution

https://github.com/tobiaslins/avatar/blob/master/src/image.js#L9

What do you think:

- generate a linear gradient using text by default
- be possible setup linear gradient using query params (start and end)

In that way, we can have a good first impression, but also powerful to customize in case you want 🙂

A variation about the default color be to use just a plain color: https://github.com/Gustu/string-to-color

**Comment by danielbachhuber** [comment]
I'm amenable to that approach.

Where would you like the functions stored, and do you have any other code structure suggestions before I finish this up?

**Comment by Kikobeats** [comment]
just renaming it as `identicon` provider should be enough; all the code can live there 🙂

**Comment by danielbachhuber** [comment]
@Kikobeats Sorry, meant to comment too: this PR is ready.

**Comment by Kikobeats** [comment]
Thanks, let me review it quickly 🙂

**Comment by danielbachhuber** [comment]
@Kikobeats Still thinking about landing this?

**Comment by Kikobeats** [comment]
hmm I'm testing this locally and looks there are a problem related with color transformation

```
TypeError: Cannot read property '2' of undefined
    at generateGradient (/Users/kikobeats/Projects/unavatar/src/providers/identicon.js:60:43)
    at module.exports (/Users/kikobeats/Projects/unavatar/src/providers/identicon.js:79:40)
    at /Users/kikobeats/Projects/unavatar/src/index.js:44:12
    at Layer.handle [as handle_request] (/Users/kikobeats/Projects/unavatar/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kikobeats/Projects/unavatar/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/kikobeats/Projects/unavatar/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/kikobeats/Projects/unavatar/node_modules/express/lib/router/layer.js:95:5)
    at /Users/kikobeats/Projects/unavatar/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/kikobeats/Projects/unavatar/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/kikobeats/Projects/unavatar/node_modules/express/lib/router/index.js:275:10)
```

**Pull request closed without merging**
